server:
   port: 8761
eureka:
  instance:
    hostname: localhost
    securePortEnabled: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka